version: '3'
services:
  mariadb:
    build: ./mariadb
    ports:
     - "3306:3306"
  opentsdb:
    build: ./opentsdb
    ports:
     - "4242:4242"
  sandbox:
    build: ./sandbox
    ports:
     - "7001:7001"
     - "8888:8888"
